import { useEffect, useMemo, useState } from 'react'
import { confirmGame, getDailyGame, postGameFound, postGameHint } from '../../api/daily'
import { useNotification } from '../NotificationProvider'
import type { DailyGame, GameChip, GameConfirmResult } from '../../types'
import WordSearchGrid from './WordSearchGrid'

export default function DailyGamePanel({ onDone }: { onDone?: () => void }) {
  const { toast } = useNotification(); const [game, setGame] = useState<DailyGame | null>(null); const [found, setFound] = useState<GameChip[]>([])
  const [links, setLinks] = useState<Record<string, string>>({}); const [selected, setSelected] = useState<string | null>(null); const [hints, setHints] = useState<Record<string, string>>({}); const [results, setResults] = useState<GameConfirmResult[] | null>(null); const [error, setError] = useState<'learning' | 'missing' | null>(null)
  useEffect(() => { getDailyGame().then(value => { setGame(value); setFound(value.found) }).catch(err => setError(err?.response?.status === 409 ? 'learning' : 'missing')) }, [])
  const foundCells = useMemo(() => found.flatMap(chip => (chip.cells ?? []).map(([row, col]) => `${row}-${col}`)), [found])
  if (error === 'learning') return <p className="py-8 text-center text-sm text-amber-300">📚 Học bài xong mới chơi được game nhé!</p>
  if (error === 'missing') return <p className="py-8 text-center text-sm text-slate-400">Hôm nay không có game.</p>
  if (!game) return <div className="flex justify-center py-16"><div className="h-8 w-8 animate-spin rounded-full border-2 border-violet-500 border-t-transparent" /></div>
  if (results) return <div className="mx-auto max-w-2xl rounded-2xl border border-white/[.07] bg-white/[.03] p-5"><h2 className="mb-1 text-xl font-black text-white">🏁 Kết quả game</h2><p className="mb-4 text-sm text-slate-400">Đúng {results.filter(item => item.correct).length}/{results.length} cặp.</p><ul className="space-y-2">{results.map(item => <li key={item.card_id} className={`flex items-center justify-between rounded-xl p-3 text-sm ${item.correct ? 'bg-emerald-400/10 text-emerald-200' : 'bg-rose-400/10 text-rose-200'}`}><b>{item.word}</b><span>{item.meaning}</span><span>{item.correct ? '✅' : '❌'}</span></li>)}</ul></div>
  const unlinked = found.filter(chip => !(chip.card_id in links)); const allFound = found.length === game.total_words; const allLinked = Object.keys(links).length === game.total_words
  const link = (token: string) => { if (!selected) return; setLinks(previous => { const next = { ...previous }; for (const cardId of Object.keys(next)) if (next[cardId] === token) delete next[cardId]; next[selected] = token; return next }); setSelected(null) }
  return <div className="grid gap-6 lg:grid-cols-[auto,1fr]"><div><p className="mb-2 text-xs font-black uppercase text-slate-500">🔍 Tìm từ trong ô chữ ({found.length}/{game.total_words})</p><WordSearchGrid grid={game.grid} foundCells={foundCells} onSelect={selection => { void postGameFound(selection).then(match => { if (match) { setFound(previous => previous.some(chip => chip.card_id === match.card_id) ? previous : [...previous, match]); toast(`🎉 Tìm thấy: ${match.word}`, 'success') } }).catch(() => toast('Không kiểm tra được lựa chọn', 'error')) }} />{unlinked.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{unlinked.map(chip => <button key={chip.card_id} onClick={() => setSelected(chip.card_id === selected ? null : chip.card_id)} className={`rounded-full px-3 py-1 text-sm font-bold ${selected === chip.card_id ? 'bg-cyan-400/40 text-white' : 'bg-white/[.08] text-slate-200'}`}>{chip.word}</button>)}</div>}</div><div><p className="mb-2 text-xs font-black uppercase text-slate-500">🔗 Nối với nghĩa tiếng Việt</p><ul className="space-y-2">{game.meanings.map(meaning => { const cardId = Object.keys(links).find(id => links[id] === meaning.token); const word = found.find(chip => chip.card_id === cardId)?.word; return <li key={meaning.token}><button disabled={!selected && !word} onClick={() => link(meaning.token)} className={`flex w-full items-center justify-between gap-3 rounded-xl border p-3 text-left text-sm ${word ? 'border-cyan-300/40 bg-cyan-400/10' : 'border-white/[.07] bg-white/[.03]'}`}><span className="text-slate-200">{meaning.meaning}</span><span className="font-bold text-cyan-200">{word ?? hints[meaning.token] ?? ''}</span></button>{!word && <button onClick={() => void postGameHint(meaning.token).then(hint => setHints(old => ({ ...old, [meaning.token]: hint.text }))).catch(() => toast('Không lấy được gợi ý', 'error'))} className="mt-1 text-xs text-slate-500 hover:text-amber-300">💡 Gợi ý</button>}</li> })}</ul><button disabled={!allFound || !allLinked} onClick={() => void confirmGame(Object.entries(links).map(([card_id, token]) => ({ card_id, token }))).then(value => { setResults(value); onDone?.() }).catch(() => toast('Không xác nhận được kết quả', 'error'))} className="mt-4 w-full rounded-xl border border-emerald-300/25 bg-emerald-400/10 py-3 text-sm font-black text-emerald-200 disabled:opacity-40">✅ Xác nhận kết quả</button></div></div>
}
