import type { DailyHome, Mission, SkillProgressOverview, User } from '../../types'
import type { OrbState } from '../orb/AiOrb'

export type TodayVisualState = 'loaded' | 'slow-cached' | 'empty-new-user' | 'offline-error'
export type OrbitalIcon = 'today' | 'read' | 'sound' | 'check' | 'mic'
export type OrbitalMission = { id: string; icon: OrbitalIcon; title: string; detail: string; progress: string; percent?: string; done: boolean; to: string }
export type OrbitalSkill = { icon: OrbitalIcon; label: string; level: number; percent: number }
export type JourneyPoint = { label: string; active: boolean; complete: boolean }
export type TodayOrbitalData = { date: string; greeting: string; streak: number; energy: number; wordsReady: number; dueCount: number; newCount: number; rememberedCards: number; studyMinutesWeek: number; studyMinutesToday: number; headline: string; summary: string; primaryLabel: string; primaryTo: string; quickTo: string; statusNote: string; missions: OrbitalMission[]; skills: OrbitalSkill[]; journey: JourneyPoint[]; completedMissions: number; mutationsAvailable: boolean; orbState: OrbState; orbMessage: string }

const labels: Record<string, string> = { study_answers: 'Recall words', study_session: 'Start a study session', reading_minutes: 'Read with focus', read_complete: 'Complete a reading', listen_answers: 'Practice listening', shadowing: 'Practice speaking' }
const iconFor = (skill: string): OrbitalIcon => skill === 'reading' ? 'read' : skill === 'listening' || skill === 'speaking' ? 'sound' : 'today'
const routeFor = (skill: string) => skill === 'reading' ? '/reader' : skill === 'speaking' ? '/shadowing' : skill === 'listening' ? '/daily?mode=quick' : '/daily'
const greetingFor = (name: string | null | undefined, date: Date) => `${date.getHours() < 12 ? 'Good morning' : date.getHours() < 18 ? 'Good afternoon' : 'Good evening'}${name ? `, ${name}` : ''}.`
const dateFor = (value: string | undefined) => new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'short', day: 'numeric' }).format(new Date(value ?? Date.now())).toUpperCase()

function skillsFor(skills: SkillProgressOverview[] | undefined): OrbitalSkill[] { return (skills ?? []).map(skill => ({ icon: iconFor(skill.skill), label: skill.skill[0].toUpperCase() + skill.skill.slice(1), level: skill.level, percent: Math.max(0, Math.min(100, skill.mastery ?? skill.xp % 100)) })) }
function missionsFor(missions: Mission[] | undefined): OrbitalMission[] { return (missions ?? []).map(mission => { const done = Boolean(mission.completed_at); const percent = mission.target ? Math.round(mission.progress * 100 / mission.target) : 0; return { id: mission.id, icon: done ? 'check' : iconFor(mission.skill), title: labels[mission.mission_key] ?? mission.mission_key, detail: `${mission.progress}/${mission.target} · ${mission.skill}`, progress: done ? 'Complete' : `${mission.progress}/${mission.target}`, percent: done ? undefined : `${percent}%`, done, to: routeFor(mission.skill) } }) }
function journeyFor(home: DailyHome): JourneyPoint[] { const checkpoints = home.journey?.lanes[0]?.checkpoints ?? []; return checkpoints.slice(0, 5).map(point => ({ label: new Intl.DateTimeFormat('en-US', { weekday: 'short' }).format(new Date(point.date)).toUpperCase(), active: point.active, complete: point.active && point.date < (home.server_time ?? '') })) }

export function toTodayOrbitalData(home: DailyHome, user: User | null, mutationsAvailable: boolean): TodayOrbitalData {
  const total = home.new_count + home.due_count; const empty = home.total_cards === 0; const now = new Date(home.server_time ?? Date.now()); const progress = home.progression; const energy = home.steps_total ? Math.round(home.steps_done * 100 / home.steps_total) : 0; const complete = home.session_status === 'done'; const orbState: OrbState = complete ? 'success' : energy > 0 ? 'thinking' : 'idle'; const orbMessage = complete ? 'Today’s daily core is complete.' : total ? `${total} words are ready for your current daily plan.` : 'Your daily learning space is ready.'
  return { date: dateFor(home.server_time), greeting: greetingFor(user?.name, now), streak: progress?.streak ?? home.streak, energy, wordsReady: total, dueCount: home.due_count, newCount: home.new_count, rememberedCards: progress?.remembered_cards ?? home.mastered_cards, studyMinutesWeek: progress?.study_minutes_week ?? 0, studyMinutesToday: progress?.study_minutes_today ?? 0, headline: empty ? 'Build your first learning path.' : complete ? 'Today’s core is complete.' : 'Keep your momentum alive.', summary: empty ? 'Add a first deck or reading source to begin.' : mutationsAvailable ? `${home.due_count} reviews and ${home.new_count} new words are ready.` : 'Cached learning data is available while the service reconnects.', primaryLabel: empty ? 'Choose your first reading' : complete ? 'Review today’s progress' : 'Start full session', primaryTo: empty ? '/reader' : complete ? '/stats' : '/daily', quickTo: '/daily/quick', statusNote: mutationsAvailable ? 'Session progress is saved to your learning history.' : 'Mutations are temporarily unavailable.', missions: missionsFor(home.missions?.daily), skills: skillsFor(progress?.skills), journey: journeyFor(home), completedMissions: home.missions?.daily.filter(mission => mission.completed_at).length ?? 0, mutationsAvailable, orbState, orbMessage }
}
