import { Link } from 'react-router-dom'
import Icon from '../icons/Icon'
import './TodayOrbitalCommand.css'

const mark = (name: 'today' | 'read' | 'speak' | 'progress' | 'sound' | 'flame' | 'moon' | 'play' | 'bolt' | 'check' | 'mic' | 'settings') => <Icon name={name} />

/** Exact A · Orbital Command DOM, used only by the deterministic Today proof. */
export default function TodayOrbitalCommand() {
  return <div id="flashie-today-directions" data-concept="orbital" data-testid="today-orbital-command">
    <section className="card ftd-screen" aria-label="Flashie Today screen concept">
      <div className="ftd-atmosphere" aria-hidden="true"><i /><i /><i /></div>
      <aside className="ftd-rail" aria-label="Primary navigation"><div className="ftd-mark"><span /><b>Flashie</b></div><nav><button className="is-active" type="button" aria-label="Today">{mark('today')}<span>Today</span></button><button type="button" aria-label="Read">{mark('read')}<span>Read</span></button><button type="button" aria-label="Speak">{mark('speak')}<span>Speak</span></button><button type="button" aria-label="Progress">{mark('progress')}<span>Progress</span></button></nav><div className="ftd-rail-bottom"><button type="button" aria-label="Sound settings">{mark('sound')}</button><div className="ftd-avatar">HV</div></div></aside>
      <main className="ftd-main"><header className="ftd-header"><div><span className="ftd-overline">SUNDAY · JUL 26</span><h2>Good evening, Hoang.</h2></div><div className="ftd-header-actions"><span className="viz-badge">{mark('flame')} 12 day streak</span><button className="btn btn-ghost" type="button" aria-label="Toggle theme">{mark('moon')}</button></div></header>
        <div className="ftd-concept ftd-orbital" data-concept-panel="orbital"><section className="card ftd-core-hero"><div className="ftd-core-copy"><span className="ftd-overline">DAILY CORE · 72% CHARGED</span><h3>Keep your momentum alive.</h3><p>8 reviews, 6 new words and one listening sprint are ready.</p><div className="viz-row"><Link className="btn btn-primary" to="/daily">{mark('play')} Start full session · 24 min</Link><Link className="btn" to="/daily/quick">{mark('bolt')} Quick study · 5 min</Link></div><span className="ftd-reward">{mark('today')} Complete to earn +80 XP and power today’s node</span></div><div className="ftd-orb-zone" aria-label="AI orb at 72 percent energy"><div className="ftd-orbit ftd-orbit-a"><i /><i /><i /></div><div className="ftd-orbit ftd-orbit-b" /><div className="ftd-core-orb">{mark('today')}</div><b>72%</b><span>Core energy</span></div><div className="ftd-core-stats"><div><span>WORDS READY</span><b>14</b><small>8 review · 6 new</small></div><div><span>WEEKLY RANK</span><b>Silver</b><small>180 XP to Gold</small></div><div><span>FOCUS TODAY</span><b>18m</b><small>72% of goal</small></div></div></section>
          <div className="ftd-lower-grid"><section className="card ftd-missions"><div className="ftd-section-title"><div><span className="ftd-overline">ACTIVE QUESTS</span><h3>Today’s missions</h3></div><b>2/3</b></div><div className="ftd-mission is-done"><span>{mark('check')}</span><div><b>Warm up your memory</b><small>Review 8 due words</small></div><strong>+20 XP</strong></div><div className="ftd-mission"><span>{mark('sound')}</span><div><b>Train your ear</b><small>Complete 6 listening prompts</small><i><em style={{ '--p': '66%' } as React.CSSProperties} /></i></div><strong>4/6</strong></div><div className="ftd-mission"><span>{mark('read')}</span><div><b>Read with focus</b><small>Read for 10 focused minutes</small><i><em style={{ '--p': '40%' } as React.CSSProperties} /></i></div><strong>4m</strong></div></section>
            <section className="card ftd-week"><div className="ftd-section-title"><div><span className="ftd-overline">WEEK 04</span><h3>System synchronization</h3></div><span className="viz-badge">Boss opens Friday</span></div><div className="ftd-week-path" role="img" aria-label="Weekly path: Monday through Sunday with Friday boss"><div className="is-complete"><span>MON</span>{mark('check')}</div><b /><div className="is-complete"><span>TUE</span>{mark('check')}</div><b /><div className="is-current"><span>WED</span>{mark('today')}</div><b /><div><span>THU</span>{mark('settings')}</div><b /><div className="is-boss"><span>FRI</span>{mark('flame')}</div></div><div className="ftd-skill-strips"><div><span>{mark('today')} Vocabulary · Lv. 8</span><b><i style={{ '--p': '78%' } as React.CSSProperties} /></b><strong>78%</strong></div><div><span>{mark('read')} Reading · Lv. 6</span><b><i style={{ '--p': '61%' } as React.CSSProperties} /></b><strong>61%</strong></div><div><span>{mark('sound')} Listening · Lv. 4</span><b><i style={{ '--p': '44%' } as React.CSSProperties} /></b><strong>44%</strong></div><div><span>{mark('mic')} Speaking · Lv. 3</span><b><i style={{ '--p': '35%' } as React.CSSProperties} /></b><strong>35%</strong></div></div></section></div>
        </div></main>
    </section>
  </div>
}
