import { Link } from 'react-router-dom'
import Icon from '../icons/Icon'
import './TodayOrbitalCommand.css'
import './TodayOrbitalCommandMobile.css'
import './TodayOrbitalCommandStates.css'
import type { TodayOrbitalData, TodayVisualState } from './todayOrbitalData'

const mark = (name: 'today' | 'read' | 'speak' | 'progress' | 'sound' | 'flame' | 'moon' | 'play' | 'bolt' | 'check' | 'mic' | 'settings') => <Icon name={name} />

/** Exact A · Orbital Command DOM. Data is supplied by HomePage in production and fixtures in visual QA. */
export default function TodayOrbitalCommand({ data, state = 'loaded' }: { data: TodayOrbitalData; state?: TodayVisualState }) {
  const disabled = !data.mutationsAvailable
  return <div id="flashie-today-directions" data-concept="orbital" data-state={state} data-testid="today-orbital-command">
    <section className="card ftd-screen" aria-label="Flashie Today screen concept">
      <div className="ftd-atmosphere" aria-hidden="true"><i /><i /><i /></div>
      <aside className="ftd-rail" aria-label="Primary navigation"><div className="ftd-mark"><span /><b>Flashie</b></div><nav><button className="is-active" type="button" aria-label="Today">{mark('today')}<span>Today</span></button><button type="button" aria-label="Read">{mark('read')}<span>Read</span></button><button type="button" aria-label="Speak">{mark('speak')}<span>Speak</span></button><button type="button" aria-label="Progress">{mark('progress')}<span>Progress</span></button></nav><div className="ftd-rail-bottom"><button type="button" aria-label="Sound settings">{mark('sound')}</button><div className="ftd-avatar">HV</div></div></aside>
      <main className="ftd-main"><header className="ftd-header"><div><span className="ftd-overline">{data.date}</span><h2>{data.greeting}</h2></div><div className="ftd-header-actions"><span className="viz-badge">{mark('flame')} {data.streak} day streak</span><button className="btn btn-ghost" type="button" aria-label="Toggle theme">{mark('moon')}</button></div></header>
        <div className="ftd-concept ftd-orbital" data-concept-panel="orbital"><section className="card ftd-core-hero"><div className="ftd-core-copy"><span className="ftd-overline">DAILY CORE · {data.energy}% CHARGED</span><h3>{data.headline}</h3><p>{data.summary}</p><div className="viz-row"><Link className="btn btn-primary" to={data.primaryTo} aria-disabled={disabled} onClick={disabled ? event => event.preventDefault() : undefined}>{mark('play')} {data.primaryLabel}</Link><Link className="btn" to={data.quickTo} aria-disabled={disabled} onClick={disabled ? event => event.preventDefault() : undefined}>{mark('bolt')} Quick study · 5 min</Link></div><span className="ftd-reward">{mark('today')}{data.reward}</span></div><div className="ftd-orb-zone" aria-label={`AI orb at ${data.energy} percent energy`}><div className="ftd-orbit ftd-orbit-a"><i /><i /><i /></div><div className="ftd-orbit ftd-orbit-b" /><div className="ftd-core-orb">{mark('today')}</div><b>{data.energy}%</b><span>Core energy</span></div><div className="ftd-core-stats"><div><span>WORDS READY</span><b>{data.wordsReady}</b><small>{`${data.reviewCount} review · ${data.newCount} new`}</small></div><div><span>WEEKLY RANK</span><b>Silver</b><small>180 XP to Gold</small></div><div><span>FOCUS TODAY</span><b>{data.focusMinutes}m</b><small>{data.energy}% of goal</small></div></div></section>
          <div className="ftd-lower-grid"><section className="card ftd-missions"><div className="ftd-section-title"><div><span className="ftd-overline">ACTIVE QUESTS</span><h3>Today’s missions</h3></div><b>{data.completedMissions}/{data.missions.length}</b></div>{data.missions.map(mission => <div className={`ftd-mission${mission.done ? ' is-done' : ''}`} key={mission.id}><span>{mark(mission.icon)}</span><div><b>{mission.title}</b><small>{mission.detail}</small>{mission.percent && <i><em style={{ '--p': mission.percent } as React.CSSProperties} /></i>}</div><strong>{mission.progress}</strong></div>)}</section>
            <section className="card ftd-week"><div className="ftd-section-title"><div><span className="ftd-overline">WEEK 04</span><h3>System synchronization</h3></div><span className="viz-badge">{data.bossAvailable ? 'Boss is open' : 'Boss opens Friday'}</span></div><div className="ftd-week-path" role="img" aria-label="Weekly path: Monday through Sunday with Friday boss"><div className="is-complete"><span>MON</span>{mark('check')}</div><b /><div className="is-complete"><span>TUE</span>{mark('check')}</div><b /><div className="is-current"><span>WED</span>{mark('today')}</div><b /><div><span>THU</span>{mark('settings')}</div><b /><div className="is-boss"><span>FRI</span>{mark('flame')}</div></div><div className="ftd-skill-strips">{data.skills.map(skill => <div key={skill.label}><span>{mark(skill.icon)} {skill.label} · Lv. {skill.level}</span><b><i style={{ '--p': `${skill.percent}%` } as React.CSSProperties} /></b><strong>{skill.percent}%</strong></div>)}</div></section></div>
        </div></main>
      <nav className="ftd-mobile-nav" aria-label="Mobile navigation"><button className="is-active" type="button" aria-label="Today">{mark('today')}<span>Today</span></button><button type="button" aria-label="Read">{mark('read')}<span>Read</span></button><button type="button" aria-label="Speak">{mark('speak')}<span>Speak</span></button><button type="button" aria-label="Progress">{mark('progress')}<span>Progress</span></button><button type="button" aria-label="More">•••<span>More</span></button></nav>
    </section>
  </div>
}
