import { useEffect, useMemo, useState } from 'react'
import { createCard } from '../../api/cards'
import { getDecks } from '../../api/decks'
import { lookupEnDictionary, lookupViDictionary } from '../../api/dictionary'
import type { Deck, DictionaryResult, EnDictResult } from '../../types'
import { useNotification } from '../NotificationProvider'

interface Props { word: string; sentence: string; onClose: () => void }
const LAST_DECK_KEY = 'reader.lastDeckId'

export default function WordPopup({ word, sentence, onClose }: Props) {
  const { toast } = useNotification(); const [vi, setVi] = useState<DictionaryResult | null | 'loading'>('loading'); const [en, setEn] = useState<EnDictResult | null | 'loading'>('loading')
  const [decks, setDecks] = useState<Deck[]>([]); const [deckId, setDeckId] = useState(() => window.localStorage.getItem(LAST_DECK_KEY) ?? ''); const [backText, setBackText] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { setVi('loading'); setEn('loading'); void lookupViDictionary(word).then(result => { setVi(result); if (result) setBackText(result.content.split('\n').find(line => line.startsWith('-'))?.replace(/^-\s*/, '') ?? result.content.slice(0, 120)) }); void lookupEnDictionary(word).then(setEn); void getDecks().then(result => { setDecks(result); if (!result.some(deck => deck.id === window.localStorage.getItem(LAST_DECK_KEY))) setDeckId(result[0]?.id ?? '') }) }, [word])
  const ipa = useMemo(() => vi !== 'loading' && vi?.pronunciation ? vi.pronunciation : en !== 'loading' ? en?.phonetic ?? null : null, [vi, en])
  const playAudio = () => { if (en !== 'loading' && en?.audioUrl) void new Audio(en.audioUrl).play().catch(() => {}); else { const utterance = new SpeechSynthesisUtterance(word); utterance.lang = 'en-US'; window.speechSynthesis.speak(utterance) } }
  const save = async () => { if (!deckId || !backText.trim()) return; setSaving(true); try { await createCard(deckId, { front_text: word, back_text: backText.trim(), example_sentence: sentence, pronunciation: ipa ?? undefined, definition: en !== 'loading' ? en?.meanings[0]?.definitions[0] : undefined, audio_url: en !== 'loading' ? en?.audioUrl ?? undefined : undefined }); window.localStorage.setItem(LAST_DECK_KEY, deckId); toast(`Đã lưu “${word}” vào bộ thẻ`, 'success'); onClose() } catch (error: any) { toast(error?.response?.data?.detail ?? 'Không lưu được thẻ', 'error') } finally { setSaving(false) } }
  return <div className="fixed inset-x-0 bottom-0 z-50 sm:inset-auto sm:right-6 sm:top-24 sm:w-96"><div className="max-h-[70vh] overflow-y-auto rounded-t-2xl border border-white/10 bg-slate-900/95 p-5 shadow-2xl backdrop-blur-xl sm:rounded-2xl"><div className="mb-3 flex items-start justify-between"><div><h3 className="text-xl font-black text-white">{word}</h3><p className="text-sm text-cyan-300">{ipa ?? ''} <button onClick={playAudio} className="ml-1 rounded px-1 hover:bg-white/10" title="Phát âm">🔊</button></p></div><button onClick={onClose} className="rounded-lg px-2 py-1 text-slate-400 hover:bg-white/10 hover:text-white">✕</button></div><div className="space-y-3 text-sm"><section><h4 className="mb-1 text-xs font-black uppercase text-slate-500">🇻🇳 Anh - Việt</h4>{vi === 'loading' ? <p className="animate-pulse text-slate-500">Đang tra…</p> : vi ? <pre className="whitespace-pre-wrap font-sans text-slate-200">{vi.content}</pre> : <p className="text-slate-500">Không có trong từ điển.</p>}</section><section><h4 className="mb-1 text-xs font-black uppercase text-slate-500">🇬🇧 English</h4>{en === 'loading' ? <p className="animate-pulse text-slate-500">Đang tra…</p> : en ? <div className="space-y-1 text-slate-200">{en.meanings.map((meaning, index) => <p key={index}><em className="text-slate-400">{meaning.partOfSpeech}.</em> {meaning.definitions.join(' · ')}</p>)}</div> : <p className="text-slate-500">Không tìm thấy.</p>}</section><section className="rounded-xl bg-black/25 p-3"><p className="text-xs italic text-slate-400">“{sentence}”</p></section></div><div className="mt-4 space-y-2 border-t border-white/10 pt-3"><select value={deckId} onChange={event => setDeckId(event.target.value)} className="w-full rounded-xl border border-white/10 bg-black/30 px-2 py-2 text-sm text-white">{decks.map(deck => <option key={deck.id} value={deck.id}>{deck.name}</option>)}</select><input value={backText} onChange={event => setBackText(event.target.value)} placeholder="Nghĩa (mặt sau thẻ)" className="w-full rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-sm text-white placeholder:text-slate-500" /><button onClick={() => void save()} disabled={saving || !deckId || !backText.trim()} className="w-full rounded-xl border border-emerald-300/25 bg-emerald-400/10 py-2 text-sm font-bold text-emerald-200 disabled:opacity-40">{saving ? 'Đang lưu…' : '💾 Lưu vào bộ thẻ (kèm câu ngữ cảnh)'}</button></div></div></div>
}
