import { useState } from 'react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'
import { useNotification } from '../components/NotificationProvider'
import AiOrb from '../components/orb/AiOrb'

export default function AuthPage({ mode }: { mode: 'login' | 'register' }) {
  const registerMode = mode === 'register'; const { user, login, register } = useAuth(); const { toast } = useNotification(); const navigate = useNavigate(); const location = useLocation(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [submitting, setSubmitting] = useState(false)
  const from = (location.state as { from?: { pathname?: string } } | null)?.from?.pathname ?? '/'
  if (user) return <Navigate to={from} replace />
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSubmitting(true); try { if (registerMode) await register(email, password, name.trim() || undefined); else await login(email, password); toast(registerMode ? 'Account created. Welcome to Flashie.' : 'Welcome back.', 'success'); navigate(registerMode ? '/onboarding' : from, { replace: true }) } catch (error: any) { toast(error.response?.data?.detail || 'We could not complete that request.', 'error') } finally { setSubmitting(false) } }
  return <main className="auth-page"><section className="glass-panel"><AiOrb state="idle" /><p className="eyebrow">Flashie Learning OS</p><h1>{registerMode ? 'Build a learning habit that fits your day.' : 'Pick up where you left off.'}</h1><p>{registerMode ? 'Set up your learning space in about two minutes.' : 'Your progress, preferences, and next step are ready.'}</p><form onSubmit={submit}>{registerMode && <label>Name<input value={name} onChange={event => setName(event.target.value)} placeholder="How should we call you?" /></label>}<label>Email<input autoFocus required type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@example.com" /></label><label>Password<input required minLength={registerMode ? 8 : undefined} type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="At least 8 characters" /></label><button className="button-primary" disabled={submitting}>{submitting ? 'Working…' : registerMode ? 'Create account' : 'Sign in'}</button></form><p className="auth-switch">{registerMode ? 'Already have an account?' : 'New to Flashie?'} <Link to={registerMode ? '/login' : '/register'}>{registerMode ? 'Sign in' : 'Create one'}</Link></p></section></main>
}
