import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { getArticle, getArticles } from '../api/articles'
import { getDecks } from '../api/decks'
import { submitReview } from '../api/review'
import { createShadowAttempt, createShadowVideo, deleteShadowVideo, getShadowCards, getShadowVideo, getShadowVideos } from '../api/shadowing'
import { fetchWorkerSubtitles, scoreRecording } from '../api/shadowingWorker'
import { useNotification } from '../components/NotificationProvider'
import ScoreDisplay from '../components/shadowing/ScoreDisplay'
import { Mp3Player, TtsPlayer, type PlayerHandle } from '../components/shadowing/SegmentPlayer'
import { YouTubePlayer } from '../components/shadowing/YouTubePlayer'
import { useRecorder } from '../components/shadowing/useRecorder'
import { useShadowingWorker } from '../hooks/useShadowingWorker'
import type { ArticleListItem, Deck, ShadowCard, ShadowScore, ShadowVideo, ShadowVideoListItem } from '../types'
import { splitSentences, stripTranscriptTimestamps } from '../utils/readerText'
import { useActivityTimer } from '../hooks/useActivityTimer'

type Source = { kind: 'card'; cards: ShadowCard[]; label: string } | { kind: 'article'; articleId: string; sentences: string[]; label: string } | { kind: 'youtube'; video: ShadowVideo; label: string }
type Tab = 'card' | 'article' | 'youtube'; type Phase = 'setup' | 'loading' | 'practice' | 'done'
const qualityFor = (score: number) => score >= 80 ? 5 : score >= 60 ? 3 : null

export default function ShadowingPage() {
  const { toast } = useNotification(), worker = useShadowingWorker(), recorder = useRecorder(), [params] = useSearchParams(); const playerRef = useRef<PlayerHandle | null>(null), autoStart = useRef(false)
  const [phase, setPhase] = useState<Phase>('setup'), [tab, setTab] = useState<Tab>('card'), [decks, setDecks] = useState<Deck[]>([]), [articles, setArticles] = useState<ArticleListItem[]>([]), [videos, setVideos] = useState<ShadowVideoListItem[]>([]), [deckScope, setDeckScope] = useState('due'), [source, setSource] = useState<Source | null>(null), [index, setIndex] = useState(0), [rate, setRate] = useState(1), [result, setResult] = useState<ShadowScore | null>(null), [scoring, setScoring] = useState(false), [scores, setScores] = useState<Record<number, number>>({}), [submitted, setSubmitted] = useState<Record<number, boolean>>({}), [youtubeUrl, setYoutubeUrl] = useState(''), [importing, setImporting] = useState(false)
  useActivityTimer({ event_type: 'duration', skill: 'speaking', source_type: 'shadowing' }, phase === 'practice')
  useEffect(() => { void getDecks().then(setDecks).catch(() => {}); void getArticles().then(setArticles).catch(() => {}); void getShadowVideos().then(setVideos).catch(() => {}) }, [])
  const sentence = useMemo(() => !source ? '' : source.kind === 'card' ? source.cards[index]?.example_sentence ?? '' : source.kind === 'article' ? source.sentences[index] ?? '' : source.video.segments[index]?.text ?? '', [source, index])
  const total = !source ? 0 : source.kind === 'card' ? source.cards.length : source.kind === 'article' ? source.sentences.length : source.video.segments.length
  const begin = useCallback((next: Source) => { setSource(next); setIndex(0); setScores({}); setSubmitted({}); setResult(null); setPhase('practice') }, [])
  const startCards = useCallback(async (options: { deckId?: string; cardId?: string }) => { setPhase('loading'); try { const cards = await getShadowCards({ ...options, dueOnly: !options.deckId && !options.cardId }); if (!cards.length) { toast('Không có thẻ nào có audio câu ví dụ phù hợp', 'warning'); setPhase('setup') } else begin({ kind: 'card', cards, label: 'Flashcards' }) } catch { toast('Không tải được thẻ', 'error'); setPhase('setup') } }, [begin, toast])
  const startArticle = useCallback(async (articleId: string) => { setPhase('loading'); try { const article = await getArticle(articleId); const sentences = splitSentences(stripTranscriptTimestamps(article.content)).filter(value => value.split(/\s+/).length >= 3); if (!sentences.length) throw new Error(); begin({ kind: 'article', articleId, sentences, label: article.title }) } catch { toast('Không tải được bài đọc phù hợp', 'error'); setPhase('setup') } }, [begin, toast])
  const startVideo = useCallback(async (id: string) => { setPhase('loading'); try { const video = await getShadowVideo(id); begin({ kind: 'youtube', video, label: video.title }) } catch { toast('Không tải được video', 'error'); setPhase('setup') } }, [begin, toast])
  useEffect(() => { if (autoStart.current) return; const card = params.get('card'), deck = params.get('deck'), article = params.get('article'); if (card) { autoStart.current = true; void startCards({ cardId: card }) } else if (deck) { autoStart.current = true; void startCards({ deckId: deck }) } else if (article) { autoStart.current = true; void startArticle(article) } }, [params, startArticle, startCards])
  const flushReview = useCallback((at: number) => { if (!source || source.kind !== 'card' || submitted[at]) return; const quality = scores[at] === undefined ? null : qualityFor(scores[at]); if (quality === null) return; setSubmitted(current => ({ ...current, [at]: true })); void submitReview(source.cards[at].id, { quality, rating_source: 'shadowing', answer_correct: true }).catch(() => toast('Không lưu được lịch ôn', 'error')) }, [scores, source, submitted, toast])
  const goTo = (next: number) => { flushReview(index); playerRef.current?.stop(); recorder.reset(); setResult(null); setIndex(next) }
  useEffect(() => { if (!recorder.blob || !sentence || worker.status !== 'online') return; setScoring(true); void scoreRecording(recorder.blob, sentence).then(score => { setResult(score); if (!score.no_speech && source) { setScores(current => ({ ...current, [index]: Math.max(current[index] ?? 0, score.score) })); void createShadowAttempt({ source_type: source.kind, card_id: source.kind === 'card' ? source.cards[index].id : null, article_id: source.kind === 'article' ? source.articleId : null, video_id: source.kind === 'youtube' ? source.video.id : null, segment_index: source.kind === 'card' ? null : index, target_text: sentence, transcript: score.transcript, score: score.score, word_results: score.words }).catch(() => {}) } }).catch(() => toast('Không chấm được điểm — kiểm tra công tắc GPU', 'error')).finally(() => setScoring(false)) }, [recorder.blob]) // eslint-disable-line react-hooks/exhaustive-deps
  const importVideo = async () => { if (!youtubeUrl.trim()) return; setImporting(true); try { const subtitles = await fetchWorkerSubtitles(youtubeUrl.trim()); const video = await createShadowVideo(subtitles); setVideos(await getShadowVideos()); setYoutubeUrl(''); begin({ kind: 'youtube', video, label: video.title }) } catch { toast('Không import được video — kiểm tra worker và link', 'error') } finally { setImporting(false) } }
  const exit = () => { flushReview(index); playerRef.current?.stop(); recorder.reset(); setSource(null); setResult(null); setPhase('setup') }
  const badge = worker.status === 'online' ? <span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-200">🟢 Worker sẵn sàng {worker.health?.device === 'cpu' && '(CPU)'}</span> : <span className="rounded-full bg-rose-400/10 px-3 py-1 text-xs font-bold text-rose-200">🔴 Công tắc đang tắt</span>
  return <main className="mx-auto max-w-2xl px-4 py-8"><div className="mb-6 flex items-center justify-between gap-3"><h1 className="text-2xl font-black text-white">🎤 Shadowing</h1>{badge}</div>
    {phase === 'setup' && <><div className="mb-5 flex gap-2">{([{ key: 'card', label: '🃏 Flashcards' }, { key: 'article', label: '📖 Bài đọc' }, { key: 'youtube', label: '▶️ YouTube' }] as { key: Tab; label: string }[]).map(item => <button key={item.key} onClick={() => setTab(item.key)} className={`rounded-xl px-3 py-2 text-sm font-bold ${tab === item.key ? 'bg-cyan-400/10 text-cyan-200' : 'bg-white/[.03] text-slate-400'}`}>{item.label}</button>)}</div>
      {tab === 'card' && <section className="rounded-2xl border border-white/[.07] bg-white/[.03] p-4"><select value={deckScope} onChange={event => setDeckScope(event.target.value)} className="mb-3 w-full rounded-xl bg-black/30 p-3 text-white"><option value="due">🔥 Thẻ đến hạn hôm nay</option>{decks.map(deck => <option key={deck.id} value={deck.id}>{deck.name}</option>)}</select><button onClick={() => void startCards(deckScope === 'due' ? {} : { deckId: deckScope })} className="w-full rounded-xl bg-cyan-400/10 py-3 font-bold text-cyan-200">Bắt đầu luyện</button></section>}
      {tab === 'article' && <div className="space-y-2">{articles.map(article => <button key={article.id} onClick={() => void startArticle(article.id)} className="block w-full rounded-2xl border border-white/[.07] bg-white/[.03] p-4 text-left font-bold text-slate-100">{article.title}<span className="block text-xs text-slate-500">{article.word_count} từ</span></button>)}</div>}
      {tab === 'youtube' && <div className="space-y-3"><div className="rounded-2xl border border-white/[.07] bg-white/[.03] p-4"><label className="mb-2 block text-xs font-bold text-slate-500">Dán link YouTube</label><div className="flex gap-2"><input value={youtubeUrl} onChange={event => setYoutubeUrl(event.target.value)} className="min-w-0 flex-1 rounded-xl bg-black/30 px-3 text-white" placeholder="https://youtube.com/..."/><button disabled={importing || worker.status !== 'online'} onClick={() => void importVideo()} className="rounded-xl bg-cyan-400/10 px-4 py-2 font-bold text-cyan-200 disabled:opacity-40">{importing ? 'Đang lấy…' : '📥 Import'}</button></div></div>{videos.map(video => <div key={video.id} className="flex items-center gap-3 rounded-2xl border border-white/[.07] bg-white/[.03] p-4"><button onClick={() => void startVideo(video.id)} className="min-w-0 flex-1 text-left font-bold text-slate-100">{video.title}<span className="block text-xs text-slate-500">{video.segment_count} câu</span></button><button onClick={() => void deleteShadowVideo(video.id).then(() => setVideos(items => items.filter(item => item.id !== video.id)))} className="text-slate-500">🗑</button></div>)}</div>}</>}
    {phase === 'loading' && <div className="h-48 animate-pulse rounded-2xl bg-white/[.05]" />}
    {phase === 'practice' && source && <section className="space-y-4"><div className="flex justify-between text-sm text-slate-400"><span>{source.label}</span><span>Sentence {index + 1}/{total}</span></div><div className="flex flex-wrap gap-1">{Array.from({ length: total }, (_, item) => <button key={item} onClick={() => item !== index && goTo(item)} className={`h-7 min-w-7 rounded ${item === index ? 'bg-cyan-400/20 text-cyan-100' : scores[item] !== undefined ? 'bg-emerald-400/10 text-emerald-200' : 'bg-white/[.04] text-slate-500'}`}>{item + 1}</button>)}</div>{source.kind === 'card' && <Mp3Player ref={playerRef} src={source.cards[index].example_audio_url} rate={rate} />}{source.kind === 'article' && <TtsPlayer ref={playerRef} text={sentence} rate={rate} />}{source.kind === 'youtube' && <YouTubePlayer ref={playerRef} videoId={source.video.youtube_id} start={source.video.segments[index].start} end={source.video.segments[index].end} rate={rate} />}<div className="rounded-2xl border border-white/[.07] bg-white/[.03] p-5 text-center"><p className="text-xl font-bold leading-9 text-white">{sentence}</p><div className="mt-4 flex flex-wrap justify-center gap-2"><button onClick={() => playerRef.current?.play()} className="rounded-xl bg-cyan-400/10 px-4 py-2 font-bold text-cyan-200">Listen</button><button onClick={() => setRate(rate === 1 ? .75 : 1)} className="rounded-xl bg-white/[.05] px-3 py-2 text-slate-300">{rate}x</button><button disabled={scoring} onClick={() => recorder.recording ? recorder.stop() : void recorder.start()} className="rounded-xl bg-emerald-400/10 px-5 py-2 font-bold text-emerald-200 disabled:opacity-40">{recorder.recording ? 'Stop' : 'Record'}</button></div>{worker.status !== 'online' && <p className="mt-3 text-xs text-amber-200">Offline mode: record, listen back, and self-compare. No score will be invented.</p>}{recorder.error && <p className="mt-3 text-rose-300">{recorder.error}</p>}</div>{scoring && <div className="h-20 animate-pulse rounded-2xl bg-white/[.05]" />}{result && !scoring && <ScoreDisplay result={result} />}<div className="flex gap-2"><button disabled={!index} onClick={() => goTo(index - 1)} className="rounded-xl bg-white/[.05] px-4 text-slate-300 disabled:opacity-30">Previous</button><button onClick={() => index + 1 < total ? goTo(index + 1) : (flushReview(index), setPhase('done'))} className="flex-1 rounded-xl bg-cyan-400/10 py-3 font-bold text-cyan-200">{index + 1 < total ? 'Next sentence' : 'Finish practice'}</button><button onClick={exit} className="px-3 text-slate-500">Exit</button></div></section>}
    {phase === 'done' && <section className="rounded-2xl border border-white/[.07] bg-white/[.03] p-5"><h2 className="text-xl font-black text-white">🏁 Kết quả phiên luyện</h2><p className="mt-2 text-slate-400">Đã chấm {Object.keys(scores).length}/{total} câu · điểm trung bình {Object.keys(scores).length ? Math.round(Object.values(scores).reduce((a, b) => a + b, 0) / Object.keys(scores).length) : 0}%</p><button onClick={exit} className="mt-4 w-full rounded-xl bg-cyan-400/10 py-3 font-bold text-cyan-200">Chọn nguồn khác</button></section>}
  </main>
}
