import { expect, test } from '@playwright/test'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const output = join(root, 'artifacts', 'visual-qa', 'today-production-integration')
const home = { new_count: 2, due_count: 3, session_status: 'none', steps_total: 10, steps_done: 5, streak: 7, studied_today: true, mastered_cards: 19, total_cards: 25, deck_count: 2, low_new_words: false, new_remaining: 2, latest_article: null, progression: { streak: 7, study_minutes_today: 11, study_minutes_week: 41, remembered_cards: 19, retention: 0.9, skills: [{ skill: 'vocabulary', xp: 52, level: 3, mastery: 52, building_signal: false }, { skill: 'reading', xp: 31, level: 2, mastery: 31, building_signal: false }], heatmap: {}, unlocks: [] }, missions: { daily: [{ id: 'm1', mission_key: 'study_answers', skill: 'vocabulary', target: 5, progress: 3, completed_at: null, rerolled: false }, { id: 'm2', mission_key: 'reading_minutes', skill: 'reading', target: 10, progress: 4, completed_at: null, rerolled: false }], weekly: [] }, journey: { week_start: '2026-07-20', timezone: 'UTC', boss_available: false, lanes: [{ skill: 'vocabulary', checkpoints: [{ date: '2026-07-20', active: true }, { date: '2026-07-21', active: true }, { date: '2026-07-22', active: false }, { date: '2026-07-23', active: false }, { date: '2026-07-24', active: false }] }] }, server_time: '2026-07-26T18:30:00Z' }
const user = { id: 'qa-user', email: 'qa@example.test', name: 'Ada', preferred_level: null, created_at: '2026-01-01T00:00:00Z', preferences: null }

async function productionSetup(page: import('@playwright/test').Page, response: unknown = home, delay = 0) {
  await page.addInitScript(({ user }) => { localStorage.setItem('flashcards.auth.token', 'redacted-qa-token'); localStorage.setItem('flashcards.auth.user', JSON.stringify(user)); localStorage.removeItem('swr:today-orbital:qa-user') }, { user })
  await page.route('**/api/auth/me', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify(user) }))
  await page.route('**/api/daily/home', async route => { if (delay) await new Promise(resolve => setTimeout(resolve, delay)); if (response === 'failure') return route.abort(); return route.fulfill({ contentType: 'application/json', body: JSON.stringify(response) }) })
}

test('production shell maps distinctive DailyHome data without proof mode', async ({ page }) => {
  mkdirSync(output, { recursive: true }); await productionSetup(page); const errors: string[] = []; page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) }); await page.setViewportSize({ width: 1440, height: 900 }); await page.goto('/'); await expect(page.locator('[data-testid="today-orbital-command"]')).toBeVisible(); await expect(page.getByText('5', { exact: true })).toBeVisible(); await expect(page.getByText('7 day streak', { exact: true })).toBeVisible(); await expect(page.getByText('11m', { exact: true })).toBeVisible(); const text = await page.locator('[data-testid="today-orbital-command"]').innerText(); expect(text).toContain('3 review · 2 new'); expect(text).not.toContain('14'); expect(text).not.toContain('12 day streak'); expect(text).not.toContain('18m'); expect(await page.locator('.ftd-rail').count()).toBe(1); expect(await page.locator('.ftd-header').count()).toBe(1); expect(await page.locator('[data-testid="today-orbital-command"] .ftd-rail').count()).toBe(0); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); expect(errors).toEqual([]); await page.screenshot({ path: join(output, 'production-1440.png') }); await page.screenshot({ path: join(output, 'single-orbital-shell-1440.png') }); writeFileSync(join(output, 'daily-home-response.redacted.json'), `${JSON.stringify(home, null, 2)}\n`); writeFileSync(join(output, 'desktop-shell-result.json'), `${JSON.stringify({ proofFlag: 'unset', rails: 1, headers: 1, overflow: false, consoleErrors: errors, values: { due_count: 3, new_count: 2, streak: 7, study_minutes_today: 11 }, pass: true }, null, 2)}\n`)
})

test('production mobile has exactly one navigation and clear first-viewport missions', async ({ page }) => {
  await productionSetup(page); await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/'); await expect(page.locator('[data-testid="today-orbital-command"]')).toBeVisible(); expect(await page.locator('.ftd-mobile-nav').count()).toBe(1); const result = await page.evaluate(() => { const nav = document.querySelector<HTMLElement>('.ftd-mobile-nav')!.getBoundingClientRect(); const first = document.querySelector<HTMLElement>('.ftd-mission')!.getBoundingClientRect(); const heading = document.querySelector<HTMLElement>('.ftd-section-title')!.getBoundingClientRect(); return { navHeight: nav.height, missionHeadingVisible: heading.top < innerHeight, firstMissionClear: first.bottom <= nav.top, noOverflow: document.documentElement.scrollWidth <= innerWidth } }); expect(result.missionHeadingVisible && result.firstMissionClear && result.noOverflow).toBeTruthy(); await page.screenshot({ path: join(output, 'production-390.png') }); writeFileSync(join(output, 'mobile-shell-result.json'), `${JSON.stringify({ proofFlag: 'unset', mobileNavigation: 1, ...result, pass: true }, null, 2)}\n`)
})

test('loading, empty, and failure never render fixture statistics', async ({ browser }) => {
  for (const [name, response, delay] of [['loading', home, 1200], ['empty', { ...home, new_count: 0, due_count: 0, streak: 0, mastered_cards: 0, total_cards: 0, progression: { ...home.progression, streak: 0, study_minutes_today: 0, remembered_cards: 0 }, missions: { daily: [], weekly: [] } }, 0], ['failure', 'failure', 0]] as const) { const context = await browser.newContext({ viewport: { width: 390, height: 844 } }); const page = await context.newPage(); await productionSetup(page, response, delay); await page.goto('/'); await expect(page.locator('[data-testid="today-orbital-command"]')).toBeVisible(); const text = await page.locator('[data-testid="today-orbital-command"]').innerText(); expect(text).not.toContain('14'); expect(text).not.toContain('12 day streak'); expect(text).not.toContain('18m'); expect(text).not.toContain('Silver'); await page.screenshot({ path: join(output, `${name}-390.png`) }); await context.close() } writeFileSync(join(output, 'no-fixture-stats-result.json'), '{"loading":true,"empty":true,"failure":true,"pass":true}\n')
})

test('production screenshot has a recorded pixel comparison to the approved reference', async ({ page }) => {
  const reference = readFileSync(join(root, 'artifacts', 'visual-qa', 'today-loaded-light-1440-proof', 'implementation.png')).toString('base64'); const actual = readFileSync(join(output, 'production-1440.png')).toString('base64'); await page.setViewportSize({ width: 1440, height: 900 }); await page.setContent('<canvas id="diff" width="1440" height="900"></canvas>'); const result = await page.evaluate(async ({ reference, actual }) => { const load = (source: string) => new Promise<HTMLImageElement>((done, fail) => { const image = new Image(); image.onload = () => done(image); image.onerror = fail; image.src = source }); const [expected, current] = await Promise.all([load(`data:image/png;base64,${reference}`), load(`data:image/png;base64,${actual}`)]); const canvas = document.querySelector<HTMLCanvasElement>('#diff')!; const context = canvas.getContext('2d')!; context.drawImage(expected, 0, 0); const left = context.getImageData(0, 0, 1440, 900); context.clearRect(0, 0, 1440, 900); context.drawImage(current, 0, 0); const right = context.getImageData(0, 0, 1440, 900); const heat = context.createImageData(1440, 900); let changed = 0; for (let index = 0; index < left.data.length; index += 4) { const delta = Math.max(...[0, 1, 2].map(offset => Math.abs(left.data[index + offset] - right.data[index + offset]))); if (delta > 10) { changed++; heat.data.set([235, 48, 48, 255], index) } else heat.data.set([right.data[index] / 3, right.data[index + 1] / 3, right.data[index + 2] / 3, 255], index) } context.putImageData(heat, 0, 0); return { reference: 'approved Today loaded/light desktop', changedPixelPercentage: Number((changed * 100 / (1440 * 900)).toFixed(4)), changedPixels: changed, totalPixels: 1440 * 900 } }, { reference, actual }); await page.locator('#diff').screenshot({ path: join(output, 'pixel-diff-heatmap.png') }); writeFileSync(join(output, 'pixel-comparison.json'), `${JSON.stringify(result, null, 2)}\n`)
})
